# Generated by Django 5.2.17 on 2026-08-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("test_drive", "حجز تجربة قيادة"),
                            ("viewing", "حجز معاينة"),
                            ("contact", "تواصل عام"),
                        ],
                        max_length=20,
                        verbose_name="نوع الطلب",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم الجوال"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الوقت المفضل"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="الرسالة/الملاحظة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الطلب"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="cars.car",
                        verbose_name="السيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
    ]
