# Generated by Django 5.2.17 on 2026-08-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[("NEW", "جديد"), ("USED", "مستعمل")],
                        max_length=4,
                        verbose_name="نوع السيارة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "متاحة"),
                            ("hidden", "مخفية"),
                            ("sold", "مباعة"),
                        ],
                        default="available",
                        max_length=10,
                        verbose_name="حالة السيارة",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="الماركة")),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="الموديل"),
                ),
                (
                    "trim",
                    models.CharField(blank=True, max_length=100, verbose_name="الفئة"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="السنة")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر",
                    ),
                ),
                (
                    "mileage_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الممشى (كم)"
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("automatic", "أوتوماتيك"), ("manual", "يدوي")],
                        max_length=20,
                        verbose_name="ناقل الحركة",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "بنزين"),
                            ("diesel", "ديزل"),
                            ("hybrid", "هايبرد"),
                            ("electric", "كهربائي"),
                        ],
                        max_length=20,
                        verbose_name="نوع الوقود",
                    ),
                ),
                (
                    "engine_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="سعة المحرك"
                    ),
                ),
                (
                    "exterior_color",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="اللون الخارجي"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة/الفرع"
                    ),
                ),
                (
                    "specification_origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("saudi", "سعودي"),
                            ("gulf", "خليجي"),
                            ("imported", "مستورد"),
                        ],
                        max_length=20,
                        verbose_name="الوارد/المواصفات",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="وصف مختصر"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "سيارة",
                "verbose_name_plural": "السيارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="cars/%Y/%m/", verbose_name="الصورة"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="صورة رئيسية"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة سيارة",
                "verbose_name_plural": "صور السيارات",
                "ordering": ["order", "id"],
            },
        ),
    ]
